// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Controllers.AccountController")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Controllers.HomeController")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.CustomLogs.AccountLog")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Data.AppUser")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Data.Migrations.AppUser")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Handlers.JwtTokenHandler")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.LoginViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.RegisterViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.VerifyEmailViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Services.IdentityTokenStorageService")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Controllers.TodoListsController")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Controllers.TodoTasksController")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.CustomLogs.TodoListsLog")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.CustomLogs.TodoTasksLog")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Data.ApplicationDbContext")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Account.ForgotPasswordViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Account.LoginViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Account.RegisterViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Account.ResetPasswordViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Account.VerifyEmailViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.List.CreateTodoListViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.List.EditTodoListViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.List.TodoListsPageViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.List.TodoListViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Tag.TagViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Task.AssignedTasksViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Task.CreateTodoTaskViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Task.EditTodoTaskViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Task.TodoTaskDetailsViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Task.TodoTasksListViewModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "Apis controllers do not work when internal.", Scope = "type", Target = "~T:TodoListApp.WebApp.Models.Task.TodoTaskViewModel")]
